name: Demo Workflow
on: [push]

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: make executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: build_docker
        run: docker build -t webserver ./Webserver && docker build -t api-server ./API-Server
