name: Demo Workflow
on: [push]

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: make executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: build_docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/esa-buildmanagement:webserver ./Webserver && docker build -t ${{ secrets.DOCKER_USERNAME }}/esa-buildmanagement:api-server ./API-Server

      - name: docker_login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: push_docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/esa-buildmanagement:webserver && docker push ${{ secrets.DOCKER_USERNAME }}/esa-buildmanagement:api-server
